// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'run FlutterFire configure for the leon-garcia Firebase project '
          'if iOS support is needed.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_z2P6t_i8d3yOFpshkNxsoRaJwicu0ww',
    appId: '1:20326824673:web:1c7250658286f08161d5a0',
    messagingSenderId: '20326824673',
    projectId: 'leon-garcia',
    authDomain: 'leon-garcia.firebaseapp.com',
    storageBucket: 'leon-garcia.firebasestorage.app',
    measurementId: 'G-G79DM53QHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQlN6OXZn6UJkysdyQNHSVWydvBC6HdHI',
    appId: '1:20326824673:android:fb0a11463ef96ab761d5a0',
    messagingSenderId: '20326824673',
    projectId: 'leon-garcia',
    storageBucket: 'leon-garcia.firebasestorage.app',
  );
}
